fixed inconsistencies in testing infra

diff --git a/bin/runbsc b/bin/runbsc
--- a/bin/runbsc
+++ b/bin/runbsc
@@ -5,13 +5,28 @@ set -e
 SCRIPTPATH=$(cd "$(dirname "$0")" && pwd -P)
 
 usage () {
-    echo "Usage: ./runbsc [v|s|c] <dir> <simout>?"
+    echo "Usage: ./runbsc -w [v|s|c] <dir> <simout>?"
+    echo "Using the -w flag will generate warnings, omitting it will suppress them."
     echo "v compiles to verilog"
     echo "s runs the bsv simulator"
     echo "c cleans up files generated by bsc"
     echo "<dir> contains all user *.bsv files generated by pdl"
     echo "<simout> is optional and specifies the name of the output file for simulation results -- defaults to top.sim.out"
 }
+
+WARN=" -suppress-warnings ALL "
+while getopts ":w" opt; do
+    case ${opt} in
+	w )
+	    WARN=""
+	    ;;
+	\? )
+	    echo "Invalid Option: -$OPTARG" 1>&2
+	    exit 1
+	    ;;
+    esac
+done
+shift $((OPTIND -1))
 
 if [[ -z "$1" ]]
 then
@@ -46,7 +61,7 @@ fi
 RUNTIMEPATH=$(cd "$SCRIPTPATH/../bscRuntime" && pwd -P)
 TOP=Circuit
 TB="mkTB"
-ARGS="-no-show-timestamps -no-show-version --aggressive-conditions"
+ARGS="$WARN""-no-show-timestamps -no-show-version --aggressive-conditions"
 BSC=$BLUESPECDIR/inst/bin/bsc
 VPATH="-vsearch $BLUESPECDIR/src/Verilog:$BLUESPECDIR/src/Verilog.Vivado:$BLUESPECDIR/src/Verilog.Quartus:$RUNTIMEPATH/verilog"
 VSIM="-vsim iverilog"
@@ -64,9 +79,9 @@ case "$CMD" in
 	;;
     "s")
 	#Run simulation in Verilog
-	"$BSC" $ARGS $BPATH $VPATH $VSIM -simdir $SDIR -u "$TOP".bsv
-	"$BSC" $ARGS $VPATH $VSIM -verilog -simdir $SDIR -o "$TB".bexe -e "$TB" "$TB".v
-	timeout 10s ./"$TB".bexe > "$SIMOUT"
+	"$BSC" $ARGS $BPATH $VPATH $VSIM -vdir $VDIR -simdir $SDIR -u "$TOP".bsv
+	"$BSC" $ARGS $VPATH $VSIM -verilog -vdir $VDIR -simdir $SDIR -o "$TB".bexe -e "$TB" "$TB".v
+	timeout 10s ./"$TB".bexe | grep -v "WARNING" > "$SIMOUT"
 	;;
     "c")
 	rm -f *.bi *.bo *.ba
